name: Example Release Workflow

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create a new release
        run: |
          echo "github.event.release.released: ${{ github.event.release.released }}"
          echo "github.event.release.prereleased: ${{ github.event.release.prereleased }}"
